# possible values:
# https://github.com/bbatsov/rubocop/blob/master/config/

CyclomaticComplexity:
  Max: 9
  Severity: refactor
PerceivedComplexity:
  Max: 9
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 8
#
# Enabled/Disabled
#
Style/Alias:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
ModuleLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SignalException:
  Enabled: false